[versions]
react = "17.0.2-pre.265-kotlin-1.5.31"
css = "1.0.0-pre.265-kotlin-1.5.31"
styled = "5.3.3-pre.265-kotlin-1.5.31"
router = "5.3.0-pre.265-kotlin-1.5.31"

[libraries]
react = { module = "org.jetbrains.kotlin-wrappers:kotlin-react", version.ref = "react" }
router = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom", version.ref = "router" }
css = { module = "org.jetbrains.kotlin-wrappers:kotlin-css", version.ref = "css" }
styled = { module = "org.jetbrains.kotlin-wrappers:kotlin-styled", version.ref = "styled" }