name: Build & Test

on:
  push:
    branches: [ master ]

env:
  ASOFT_MAVEN_PGP_PRIVATE_KEY: ${{ secrets.ASOFT_MAVEN_PGP_PRIVATE_KEY }}
  ASOFT_MAVEN_PGP_PASSWORD: ${{ secrets.ASOFT_MAVEN_PGP_PASSWORD }}
  ASOFT_NEXUS_PASSWORD: ${{ secrets.ASOFT_NEXUS_PASSWORD }}
  ASOFT_NEXUS_USERNAME: ${{ secrets.ASOFT_NEXUS_USERNAME }}

jobs:
  publish-artifacts:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/yarn
            ~/.gradle/nodejs
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/gradle-wrapper.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
          key: ${{ runner.os }}-konan-
          restore-keys: ${{ runner.os }}-konan-
      - name: Making gradlew executable
        run: chmod +x ./gradlew
        working-directory: .
      - name: Warm up the jvm
        run: ./gradlew tasks
        working-directory: .
      - name: Building the project
        run: ./gradlew build
        working-directory: .
      - name: Publishing artifacts to sonatype
        run: ./gradlew publish
      - name: Closing and Releasing Repositories
        run: ./gradlew :viewmodel-core:closeAndReleaseRepository
        working-directory: .
      - name: Create Release
        run: ./gradlew createRelease
